### ISSUE TITLE
Document description

### ISSUE THREAD

**Issue by xwb123** [Shun14/psenet_tf#1]
Can you give a description of the document?

**Comment by Shun14** [comment]
> Can you give a description of the document?

Sorry, I am just reimplementing the paper now, so the document is empty.

**Comment by xwb123** [comment]
![image](https://user-images.githubusercontent.com/9149549/49071199-692ede80-f268-11e8-93de-35f37ee143cc.png)

**Comment by xwb123** [comment]
Is the function shown on the diagram?

**Comment by Shun14** [comment]
> Is the function shown on the diagram?

Yeah, you're right.

**Comment by xwb123** [comment]
My English is not very good. Can I communicate with you in Chinese?

**Comment by Shun14** [comment]
> My English is not very good. Can I communicate with you in Chinese?

Fine.

**Comment by xwb123** [comment]
您好：看网络模型，前半部分是FPN提取4个尺度的特征图，然后做融合，送入F中，分类出不同宽度的分割效果。这个F是采用的什么网络？还有就是训练的时候制作训练集，这种弯曲的区域如何标识，不能用简单的正方形两个顶点坐标了。希望给予解答，谢谢

**Comment by Shun14** [comment]
> 您好：看网络模型，前半部分是FPN提取4个尺度的特征图，然后做融合，送入F中，分类出不同宽度的分割效果。这个F是采用的什么网络？还有就是训练的时候制作训练集，这种弯曲的区域如何标识，不能用简单的正方形两个顶点坐标了。希望给予解答，谢谢

对于第一个问题，我看论文中FPN采用的模型是resnet，可以用resnet101和resnet50。F按照论文的描述是四个尺度的特征图融合之后的结果，随后F经过一串conv1x1层输出分割图。
第二个问题：文章里提到了采用了the Vatti clipping algorithm 去做弯曲图片的切片图,目前我的代码里面只加了水平文本的代码。我刚刚找了下，python里面有个库可以完成这个工作pyclipper，你可以用这个库

**Comment by xwb123** [comment]
你好，你有没有弯曲文本的代码，能分享一下吗

**Comment by Shun14** [comment]
> 你好，你有没有弯曲文本的代码，能分享一下吗

你可以使用rdp这个python库，我目前还没有写弯曲的代码
